-- BOARD 테이블 생성
CREATE TABLE BOARD(
    BNO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(400) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    WRITER VARCHAR2(20),
    DELETE_YN CHAR(2) DEFAULT 'N',
    FOREIGN KEY (WRITER) REFERENCES MEMBER(MEMBER_ID),
    CHECK(DELETE_YN IN('Y','N'))
);

-- BOARD 테이블의 PK로 사용될 시퀀스
CREATE SEQUENCE SEQ_BOARD;
